# Generated by Django 4.2.6 on 2023-10-09 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Publicacione',
            new_name='Publicaciones',
        ),
    ]
