# Generated by Django 4.2.6 on 2023-10-09 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0002_rename_publicacione_publicaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicaciones',
            name='cantidad',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='publicaciones',
            name='email_contacto',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='publicaciones',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='publicaciones',
            name='telefono_contacto',
            field=models.IntegerField(null=True),
        ),
    ]
