# Generated by Django 4.2.6 on 2023-10-10 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0003_publicaciones_cantidad_publicaciones_email_contacto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicaciones',
            name='cantidad',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='publicaciones',
            name='email_contacto',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='publicaciones',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='publicaciones',
            name='telefono_contacto',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
