# Generated by Django 4.2.6 on 2023-10-10 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad', '0002_casascomunidad_miembro_casa_comarca'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='miembro',
            options={'verbose_name': 'Miembro', 'verbose_name_plural': 'Miembros'},
        ),
    ]
