# Generated by Django 4.2.6 on 2023-10-10 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad', '0003_alter_miembro_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='casascomunidad',
            options={'verbose_name': 'Casa', 'verbose_name_plural': 'Casas'},
        ),
    ]
