# Generated by Django 4.2.6 on 2023-10-10 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad', '0004_alter_casascomunidad_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miembro',
            name='casa_comarca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='comunidad.casascomunidad', verbose_name='Hogar en la comarca'),
        ),
    ]
