# Generated by Django 4.2.5 on 2023-10-11 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad', '0005_alter_miembro_casa_comarca'),
    ]

    operations = [
        migrations.AddField(
            model_name='miembro',
            name='email',
            field=models.EmailField(default=1, max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
